# 修改或新增的文件：
# 补充代码：app/checkout/biz/service/checkout.go, app/order/biz/service/list_order.go, app/order/biz/service/place_order.go
# 三种不同连接方式的配置写在八个服务的xxx/.env, xxx/conf/dev/conf.yaml, xxx/go.mod文件中
# 八个服务各自的xxx/Dockerfile
# 将rpc_gen复制到这八个服务的文件夹里
# 中间件（数据持久化）：gomall-middlewares/docker-compose.yaml
# 三个windows脚本：create-containers.bat, start-containers.bat, stop-containers.bat
# 编排这八个容器并挂载到与中间件同一网络中：docker-compose.yaml

# 推送到DockerHub的镜像：
# https://hub.docker.com/repository/docker/jinyilei/<tag>
# <tag> = gomall-cart, gomall-checkout, gomall-email, gomall-frontend, 
# gomall-order, gomall-payment, gomall-product, gomall-user
# gomall-consul, gomall-nats, gomall-mysql, gomall-redis

# 三种连接方式：
# 宿主机启动8个服务 + 容器启动4个中间件：127.0.0.1:port  
# 宿主机与容器互通用：host.docker.internal:port 
# 容器启动8个服务 + 容器启动4个中间件：gomall-xxx:port

services:
  cart:
    container_name: gomall-cart
    build:
      context: app/cart
      dockerfile: Dockerfile
    networks:
      - gomall
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=gomall-mysql   
    # depends_on:
      # - 
    # ports:
      # - "8883:8883"
      # - "9993:9993"
    # volumes:
      # -

  checkout:
    container_name: gomall-checkout
    build:
      context: app/checkout
      dockerfile: Dockerfile
    networks:
      - gomall
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=gomall-mysql   
      - REGISTRY_ADDR=gomall-consul:8500
    # depends_on:
      # - 
    # ports:
      # - "8884:8884"
      # - "9994:9994"
    # volumes:
      # -

  email:
    container_name: gomall-email
    build:
      context: app/email
      dockerfile: Dockerfile
    networks:
      - gomall
    # environment:
      # -
    # depends_on:
      # - 
    # ports:
      # - 8888:8888
    # volumes:
      # -

  frontend:
    container_name: gomall-frontend
    build:
      context: app/frontend
      dockerfile: Dockerfile
    networks:
      - gomall
    ports:
      - 8180:8180
      # - 8090:8090
    # environment:
      # -
    # depends_on:
      # - 
    # volumes:
      # -
      
  order:
    container_name: gomall-order
    build:
      context: app/order
      dockerfile: Dockerfile
    networks:
      - gomall
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=gomall-mysql
      - REGISTRY_ADDR=gomall-consul:8500
    # ports:
      # - 8885:8885
      # - 9995:9995  
    # depends_on:
      # - 
    # volumes:
      # -

  payment:
    container_name: gomall-payment
    build:
      context: app/payment
      dockerfile: Dockerfile
    networks:
      - gomall
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=gomall-mysql   
    # ports:
      # - 8886:8886
      # - 9996:9996  
    # depends_on:
      # - 
    # volumes:
      # -

  product:
    container_name: gomall-product
    build:
      context: app/product
      dockerfile: Dockerfile
    networks:
      - gomall
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=gomall-mysql
      - REGISTRY_ADDR=gomall-consul:8500   
    # ports:
      # - 8881:8881
      # - 9991:9991  
    # depends_on:
      # - 
    # volumes:
      # -
      
  user:
    container_name: gomall-user
    build:
      context: app/user
      dockerfile: Dockerfile
    networks:
      - gomall
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=gomall-mysql   
    # ports:
      # - 8882:8882
      # - 9992:9992  
    # depends_on:
      # - 
    # volumes:
      # -

networks:
  gomall:
    external: true

# volumes: